function formatComment(findings, prNumber) {
  const critical = findings.filter(f => 
    f.vulnerabilities.some(v => v.severity === 'CRITICAL')
  );
  const high = findings.filter(f => 
    f.vulnerabilities.some(v => v.severity === 'HIGH')
  );
  const medium = findings.filter(f => 
    f.vulnerabilities.some(v => v.severity === 'MEDIUM')
  );
  const low = findings.filter(f => 
    f.vulnerabilities.some(v => v.severity === 'LOW')
  );

  let comment = `## 🔒 Dependency Vulnerability Scan\n\n`;
  comment += `**Pull Request**: #${prNumber}\n`;
  comment += `**Scan Date**: ${new Date().toLocaleString()}\n\n`;

  if (critical.length > 0) {
    comment += `### 🚨 Critical Vulnerabilities Found!\n\n`;
    comment += formatVulnerabilityList(critical);
  }

  if (high.length > 0) {
    comment += `### ⚠️ High Severity Vulnerabilities\n\n`;
    comment += formatVulnerabilityList(high);
  }

  if (medium.length > 0) {
    comment += `### 📊 Medium Severity Vulnerabilities\n\n`;
    comment += formatVulnerabilityList(medium);
  }

  if (low.length > 0) {
    comment += `### ℹ️ Low Severity Vulnerabilities\n\n`;
    comment += formatVulnerabilityList(low);
  }

  if (findings.length === 0) {
    comment += `✅ **No known vulnerabilities found!** Great job! 🎉\n\n`;
  }

  // Summary section
  comment += `\n---\n`;
  comment += `### 📈 Summary\n`;
  comment += `- Total vulnerable dependencies: ${findings.length}\n`;
  if (critical.length > 0) comment += `- 🚨 Critical: ${critical.length}\n`;
  if (high.length > 0) comment += `- ⚠️ High: ${high.length}\n`;
  if (medium.length > 0) comment += `- 📊 Medium: ${medium.length}\n`;
  if (low.length > 0) comment += `- ℹ️ Low: ${low.length}\n`;

  // Quick fix section
  if (findings.length > 0) {
    comment += `\n### 🔧 Recommended Fixes\n`;
    comment += `\`\`\`bash\n`;
    const uniquePackages = [...new Set(findings.map(f => f.package))];
    for (const pkg of uniquePackages) {
      const finding = findings.find(f => f.package === pkg);
      if (finding.recommendedFix) {
        comment += `# Update ${pkg} to ${finding.recommendedFix}\n`;
        comment += `npm install ${pkg}@${finding.recommendedFix}\n`;
      } else {
        comment += `# Check ${pkg} for available updates\n`;
        comment += `npm outdated ${pkg}\n`;
      }
    }
    comment += `\`\`\`\n`;
    
    comment += `\n💡 **Tip**: Run \`npm audit fix\` or update your dependencies manually.\n`;
  }

  comment += `\n📚 **More info**: [OSV Database](https://osv.dev/) | [npm audit](https://docs.npmjs.com/cli/v10/commands/npm-audit)\n`;
  comment += `\n---\n`;
  comment += `*🤖 This comment was automatically generated by the Dependency Vulnerability Bot*`;

  return comment;
}

function formatVulnerabilityList(findings) {
  let text = '';
  
  for (const finding of findings) {
    text += `**📦 ${finding.package}** (current: \`${finding.currentVersion}\`)\n`;
    
    if (finding.recommendedFix) {
      text += `  ✅ **Fix**: Update to \`${finding.recommendedFix}\`\n`;
    }
    
    for (const vuln of finding.vulnerabilities) {
      text += `  - \`${vuln.id}\`\n`;
      text += `    📝 ${vuln.summary}\n`;
      if (vuln.cve) {
        text += `    🔗 CVE: ${vuln.cve}\n`;
      }
      if (vuln.fixedVersion) {
        text += `    ✅ Fixed in: \`${vuln.fixedVersion}\`\n`;
      }
      if (vuln.references && vuln.references.length > 0) {
        text += `    📚 References: ${vuln.references.slice(0, 2).join(', ')}\n`;
      }
      text += `    ⚡ Severity: **${vuln.severity}**\n`;
    }
    text += `\n`;
  }
  
  return text;
}

function formatErrorComment(errorMessage) {
  return `## ❌ Error Scanning Dependencies

**Error**: ${errorMessage}

This could be due to:
- Invalid package.json or requirements.txt format
- Network issues connecting to vulnerability databases
- Rate limiting from API services

**Next Steps**:
1. Check your dependency files for syntax errors
2. Try running the scan again later
3. Contact the bot maintainer if the issue persists

*🤖 This comment was automatically generated by the Dependency Vulnerability Bot*`;
}

function generateMarkdownTable(findings) {
  let table = '| Package | Current Version | Severity | Vulnerability | Fixed Version |\n';
  table += '|---------|----------------|----------|---------------|---------------|\n';
  
  for (const finding of findings) {
    for (const vuln of finding.vulnerabilities) {
      table += `| ${finding.package} | ${finding.currentVersion} | ${vuln.severity} | ${vuln.summary.slice(0, 50)}... | ${vuln.fixedVersion || 'N/A'} |\n`;
    }
  }
  
  return table;
}

module.exports = { 
  formatComment, 
  formatErrorComment, 
  formatVulnerabilityList,
  generateMarkdownTable
};